import { z } from "zod";
import { Prisma } from "@prisma/client";
import { requireYard, parseBody, ok, fail } from "@/backend/http/api";
import { nextCounter, formatLot } from "@/backend/services/counters";
import { publishMany } from "@/backend/realtime/realtime";
import { loadRef } from "@/shared/load-ref";
import { ensureShortCode } from "@/backend/services/yard-short-code";
import { initialLineStatus, initialLoadStatus } from "@/shared/material-kind";

export const dynamic = "force-dynamic";

const schema = z.object({
  /**
   * Idempotency key generated by the client per SAVE LOAD attempt. Retrying the
   * same save (double tap, flaky mobile connection, browser retry) returns the
   * original lot instead of creating a second one and double-counting stock.
   * Optional so older clients keep working unchanged.
   */
  clientRequestId: z.string().min(8).max(64).optional(),
  /**
   * Legacy single-material form. Still accepted verbatim so older clients (and
   * the existing test suites) keep working; it is normalised into `lines` below.
   */
  materialSkuId: z.string().min(1).optional(),
  entries: z.array(z.number().int().positive()).min(1).max(50).optional(),
  /**
   * The load cart: one item per "Add To Cart" tap. Several items may name the
   * same material — they are grouped by SKU at commit so each material ends up
   * with exactly one line and one traceable InventoryLot.
   *
   * `kg` is always kilograms. The keypad may capture Ton/Tonne, but the unit is
   * converted client-side and never crosses this boundary.
   *
   * `ratePerKg` is the purchase rate agreed for THAT cart item. It stays on the
   * item rather than the material because the same material can be bought twice
   * off one vehicle at two different rates; the weighment rows below are what
   * preserve that distinction through the SKU grouping.
   */
  lines: z
    .array(
      z.object({
        skuId: z.string().min(1),
        kg: z.number().int().positive(),
        ratePerKg: z.number().min(0).max(1_000_000).optional().nullable(),
      })
    )
    .min(1)
    .max(50)
    .optional(),
  vendorId: z.string().min(1).optional().nullable(),
  /**
   * Did the vendor supply an invoice / challan? Optional so older clients keep
   * working, and tri-state on the way in for the same reason it is tri-state in
   * the schema: an omitted answer is "not recorded", not "no".
   */
  hasInvoice: z.boolean().optional().nullable(),
  invoiceNumber: z.string().trim().max(60).optional().nullable(),
  invoiceUrl: z.string().max(600).optional().nullable(),
  vehicleNumber: z.string().max(20).optional().nullable(),
  vehicleType: z.string().max(30).optional().nullable(),
  driverName: z.string().max(80).optional().nullable(),
  // Same 15-character cap as Sale.driverPhone, which this mirrors.
  driverPhone: z.string().trim().max(15).optional().nullable(),
  ocrConfidence: z.number().min(0).max(1).optional().nullable(),
  frontImageUrl: z.string().max(600).optional().nullable(),
  backImageUrl: z.string().max(600).optional().nullable(),
  materialImageUrls: z.array(z.string().max(600)).max(20).optional().default([]),
  weighbridgeSlipUrl: z.string().max(600).optional().nullable(),
});

export async function POST(req: Request) {
  const guard = await requireYard();
  if ("res" in guard) return guard.res;
  const { prisma, yardId } = guard;

  const body = await parseBody(req, schema);
  if ("res" in body) return body.res;
  const d = body.data;

  // Normalise both request shapes to a single cart. The legacy form is one
  // material repeated across its weighments; the new form already is a cart.
  const cart: { skuId: string; kg: number; ratePerKg?: number | null }[] =
    d.lines && d.lines.length > 0
      ? d.lines
      : d.materialSkuId && d.entries && d.entries.length > 0
        ? d.entries.map((kg) => ({ skuId: d.materialSkuId!, kg }))
        : [];

  if (cart.length === 0) return fail("EMPTY_LOAD", "Add at least one weighment", 422);

  const total = cart.reduce((a, b) => a + b.kg, 0);
  if (total <= 0) return fail("EMPTY_LOAD", "Add at least one weighment", 422);

  /**
   * "Invoice: Yes" has to mean the document is actually there.
   *
   * Recording the answer without the upload would leave a load claiming
   * paperwork that nothing can produce, so a YES with no stored image is
   * rejected outright, and the number/image are only kept when the answer is
   * YES — a NO can never drag along a contradictory attachment.
   */
  if (d.hasInvoice === true && !d.invoiceUrl) {
    return fail("INVOICE_MISSING", "Attach the invoice / challan, or answer No", 422);
  }
  const hasInvoice = d.hasInvoice ?? null;
  const invoiceNumber = hasInvoice === true ? (d.invoiceNumber?.trim() || null) : null;
  const invoiceUrl = hasInvoice === true ? (d.invoiceUrl ?? null) : null;

  /**
   * The yard's short code, which leads the user-facing load reference.
   *
   * `ensureShortCode` assigns one only if the yard has none, so this is a plain
   * read for every yard after the first time — and it guarantees that no load
   * can ever be saved into a yard that has no stable code to be referenced by.
   * One lookup, reused by the replay answers and the success answer alike; see
   * src/shared/load-ref.ts for why the reference is composed rather than stored.
   */
  const shortCode =
    (await ensureShortCode(prisma, yardId)) ??
    (await prisma.yard.findUnique({ where: { id: yardId }, select: { yardCode: true } }))?.yardCode ??
    "";

  // Replay check before doing any work. The unique index on
  // (yardId, clientRequestId) is the race-condition backstop below.
  if (d.clientRequestId) {
    const existing = await prisma.inwardLoad.findFirst({
      where: { clientRequestId: d.clientRequestId },
      select: { lotNumber: true, totalKg: true, materialLabel: true, createdAt: true },
    });
    if (existing) {
      return ok(
        { load: { ...existing, loadRef: loadRef({ shortCode, lotNumber: existing.lotNumber }) }, replayed: true },
        { status: 200 }
      );
    }
  }

  /**
   * Every cart item must name a real, bookable material in THIS yard. One query
   * for all of them; the scoped client already constrains it to the yard, so a
   * SKU belonging to another yard simply does not come back and the count check
   * below rejects the request.
   *
   * BOTH kinds are bookable now:
   *
   *   • a MIXED bucket  — a vehicle of unsorted material, which Sort segregates;
   *   • a DIRECT sub-material — a vehicle of one finished grade, which needs no
   *     segregation and goes straight into that sub-material's stock.
   *
   * What is refused is a RETIRED material: `visible: false` is how a sort type
   * is taken out of service, and booking new stock into one would resurrect a
   * category the yard has deliberately stopped using.
   */
  const skuIds = [...new Set(cart.map((c) => c.skuId))];
  const buckets = await prisma.sku.findMany({ where: { id: { in: skuIds } } });
  if (buckets.length !== skuIds.length) {
    return fail("BAD_MATERIAL", "Invalid inward material", 422);
  }
  const retired = buckets.find((b) => !b.visible);
  if (retired) {
    return fail("BAD_MATERIAL", `"${retired.name}" is no longer available for inward`, 422);
  }
  const bucketById = new Map(buckets.map((b) => [b.id, b]));

  /**
   * Group the cart by material, preserving the order the operator entered them.
   * Two taps of "Mixed MS" become one line of the combined weight, so Sort sees
   * one row per material and stock keeps one batch per material per load.
   */
  const lines = skuIds.map((skuId, i) => {
    const b = bucketById.get(skuId)!;
    return {
      sequence: i + 1,
      skuId,
      materialId: b.materialId,
      materialLabel: b.name,
      quantityKg: cart.filter((c) => c.skuId === skuId).reduce((a, c) => a + c.kg, 0),
      /**
       * Mixed → RECEIVED, so Sort picks it up. Direct → SEGREGATED, because a
       * finished grade arrives with nothing left to segregate. See
       * src/shared/material-kind.ts for why this reuses the existing enum
       * rather than adding a third value.
       */
      status: initialLineStatus(b),
    };
  });

  // The load's own material fields stay populated for every reader written
  // before lines existed (Sort's legacy filter, admin tables, dashboards).
  // For a multi-material load the label is a display-only summary.
  const primary = bucketById.get(lines[0].skuId)!;
  const loadLabel = lines.length === 1 ? primary.name : `${primary.name} +${lines.length - 1}`;

  if (d.vendorId) {
    const vendor = await prisma.vendor.findUnique({ where: { id: d.vendorId } });
    if (!vendor) return fail("BAD_VENDOR", "Vendor not found", 422);
  }

  let result;
  try {
    result = await prisma.$transaction(async (tx) => {
    const seq = await nextCounter(tx, yardId, "lot");
    const lotNumber = formatLot(seq);

    const load = await tx.inwardLoad.create({
      data: {
        yardId,
        clientRequestId: d.clientRequestId ?? null,
        lotNumber,
        vendorId: d.vendorId ?? null,
        materialId: primary.materialId,
        materialLabel: loadLabel,
        totalKg: total,
        vehicleNumber: d.vehicleNumber ?? null,
        vehicleType: d.vehicleType ?? null,
        driverName: d.driverName ?? null,
        driverPhone: d.driverPhone?.trim() || null,
        ocrConfidence: d.ocrConfidence ?? null,
        frontImageUrl: d.frontImageUrl ?? null,
        backImageUrl: d.backImageUrl ?? null,
        hasInvoice,
        invoiceNumber,
        invoiceUrl,
        weighbridgeSlipUrl: d.weighbridgeSlipUrl ?? null,
        capturedById: guard.user.id,
        // RECEIVED only while some line still owes segregation. A vehicle of
        // nothing but direct sub-materials is finished on arrival, which is
        // what keeps it out of every "pending sort" counter in the app.
        status: initialLoadStatus(lines.map((l) => bucketById.get(l.skuId)!)),
        materialImages: {
          create: (d.materialImageUrls ?? []).map((url) => ({ yardId, url })),
        },
      },
    });

    // One line, one traceable batch, one ledger entry — per material.
    const lineIdBySku = new Map<string, string>();
    for (const l of lines) {
      const line = await tx.inwardLoadLine.create({
        data: {
          yardId,
          loadId: load.id,
          sequence: l.sequence,
          skuId: l.skuId,
          materialId: l.materialId,
          materialLabel: l.materialLabel,
          quantityKg: l.quantityKg,
          status: l.status,
        },
      });
      lineIdBySku.set(l.skuId, line.id);

      await tx.inventory.upsert({
        where: { skuId: l.skuId },
        create: { yardId, skuId: l.skuId, quantityKg: l.quantityKg },
        update: { quantityKg: { increment: l.quantityKg } },
      });

      // Traceable batch, attributed to the vendor/vehicle/load. Identical for
      // both kinds: a mixed batch is consumed by segregation, a direct batch by
      // a sale — the traceability chain back to the vendor is the same one.
      await tx.inventoryLot.create({
        data: {
          yardId,
          skuId: l.skuId,
          vendorId: d.vendorId ?? null,
          vehicleNumber: d.vehicleNumber ?? null,
          sourceLoadId: load.id,
          originalKg: l.quantityKg,
          remainingKg: l.quantityKg,
        },
      });

      await tx.inventoryTransaction.create({
        data: {
          yardId,
          skuId: l.skuId,
          changeKg: l.quantityKg,
          type: "INWARD",
          refId: load.id,
          refType: "InwardLoad",
          byUserId: guard.user.id,
        },
      });
    }

    // Individual weighments keep their own row for the audit trail, each one
    // attributed to the material it was booked against — and to the rate it was
    // bought at, which the SKU grouping above would otherwise flatten away.
    for (const [i, item] of cart.entries()) {
      await tx.weightEntry.create({
        data: {
          yardId,
          loadId: load.id,
          lineId: lineIdBySku.get(item.skuId) ?? null,
          skuId: item.skuId,
          sequence: i + 1,
          kg: item.kg,
          ratePerKg: item.ratePerKg ?? null,
        },
      });
    }

      return {
        id: load.id,
        lotNumber,
        totalKg: total,
        materialLabel: loadLabel,
        skuIds,
        createdAt: load.createdAt,
      };
    });
  } catch (e) {
    // Two simultaneous saves with the same key: one commits, the other hits the
    // unique index (P2002) and is rolled back whole. Answer it with the winner's
    // lot so the operator sees one load, not an error.
    if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === "P2002" && d.clientRequestId) {
      const winner = await prisma.inwardLoad.findFirst({
        where: { clientRequestId: d.clientRequestId },
        select: { lotNumber: true, totalKg: true, materialLabel: true, createdAt: true },
      });
      if (winner) {
        return ok(
          { load: { ...winner, loadRef: loadRef({ shortCode, lotNumber: winner.lotNumber }) }, replayed: true },
          { status: 200 }
        );
      }
    }
    throw e;
  }

  // After commit: subscribers must never be able to read pre-commit state.
  publishMany(yardId, [
    { channel: "inward", action: "created", entity: "InwardLoad", entityId: result.id, actorId: guard.user.id },
    ...result.skuIds.map((skuId) => ({
      channel: "stock" as const,
      action: "updated",
      entity: "Inventory",
      entityId: skuId,
      actorId: guard.user.id,
    })),
    { channel: "sort", action: "pending-changed", entity: "InwardLoad", entityId: result.id, actorId: guard.user.id },
  ]);

  return ok(
    {
      load: {
        lotNumber: result.lotNumber,
        totalKg: result.totalKg,
        materialLabel: result.materialLabel,
        loadRef: loadRef({ shortCode, lotNumber: result.lotNumber }),
      },
    },
    { status: 201 }
  );
}
